[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar build/libs/demo-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
